---
title: "Data Visualization Project 2"
author: 
- name: Alexander Jaenisch & Rafaela Neff
  affiliation: Beuth University of Applied Science Berlin
date: "Summer Term 2018"
output: 
  html_document: 
    fig_caption: yes
    highlight: tango
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
library(knitr) #to set up options and use kable function
opts_chunk$set(echo = FALSE, cache=FALSE) #(echo = TRUE) would include all code
read_chunk('src/script.R')
```

```{r part1}
```
# Introduction

In this excersise we examine animal bites registered in the U.S from

The repository can be found on [Github](https://github.com/amidisturbing/datavis2018).

## The data



Formulars are written like this:

$$∆E76 = \sqrt{∆L^2 + ∆a^2 + ∆b^2}$$


```{r}
perceptionTable <- matrix(NA, nrow = 5, ncol = 2, byrow = FALSE)
colnames(perceptionTable) <- c("ΔE value","Perception")
deltaE <- c("<= 1.0","1 - 2", "3 - 10", "11 - 49", "100")
perception <- c("Not perceptible by human eyes.", "Perceptible through close observation.
", "Perceptible at a glance.
", "Colors are more similar than opposite
", "Colors are exact opposite
")
for (i in 1:5) {
  perceptionTable[i,"ΔE value"] <- deltaE[i]
  perceptionTable[i,"Perception"] <- perception[i]
}
kable(perceptionTable, caption = "On a typical scale, the Delta E value will range from 0 to 100.")
```


# Analysis

To analyse the given data ...



